name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      -  uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Analyze code with ruff
        run: |
          pip install ruff
          ruff $(git ls-files '*.py')
        # continue-on-error: true
      - name: Build
        run: pip install .
      - name: Test and coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=src/leaky $(git ls-files '*_test.py')